Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.media, name='media'),
    path('blog/', include('blog.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='blog'
urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog_Model(models.Model):
    title=models.CharField(max_length=100,blank=True,default="Sanjeev")
    image=models.ImageField(upload_to="media/blog/images",blank=True)
    url=models.URLField(blank=True)

portfolio/models.py
from django.db import models
class Projects(models.Model):
    title=models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image=models.ImageField(upload_to='portfolio/images/')
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title
# Create your models here.

blog/views.py
from django.shortcuts import render,redirect
from .form import Blog
from .models import Blog_Model


def all_blogs(request):
    if request.method == 'GET':
        blog_obj = Blog_Model.objects.all().order_by('-id')
        return render(request, 'blog/all_blogs.html', {'form': Blog(),'blog_obj':blog_obj})
    else:
        try:
            form = Blog(request.POST)
            newurl = form.save(commit=False)
            newurl.save()
            return redirect(request.path_info)
        except ValueError:
            return render(request, 'blog/all_blogs.html',  {'form': Blog(),'error':'Bad data passed in. Please try again'})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Projects

def media(request):
    projects=Projects.objects.all().order_by('-id')
    return render(request,'portfolio/homepage.html',{'projects':projects})

blog/templates/blog/all_blogs.html
<head>
<meta name='viewport' content='width=device-width, initial-scale=1'>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>

{% extends 'portfolio/base.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <br>
    <label class="mt-5" for="bloglink">Copy link of the blog you want to post</label>
    <div class="form-group input-group">
         <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-link"></i></span>
        </div>
        <input type="url" name="url" class="form-control" id="url" placeholder="Help provide good content for readers">
    </div>

    <button type="submit" class="btn btn-primary">Post</button>
</form>



<div class="row justify-content-center mt-3">
<div class="col-md-9 text-center">

    {% for b_obj in blog_obj%}
    <div class="mb-0">
        <h6 id="blogurl" class="normal"> <a class="nav-link" href="{{ b_obj.url}}">
         <div class="bg-light border-bottom border-info rounded">
        {% if b_obj.url %}
        {{ b_obj.url}}
        {% endif %}
         </div>
        </a> </h6></div>
    {% endfor %}
</div>
</div>


{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <script src="https://kit.fontawesome.com/cbbb7575de.js" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" />
  <link rel="stylesheet" href="css/style.css">

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}" >

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/sanjeev.png" %}">

  <title>Sanjeev's</title>
</head>

<body>


  <nav id="topNav" class="clearfix fixed-top navbar navbar-expand-sm navbar-light">
    <div class="container">

        <a class="navbar-brand" href="{% url 'media' %}">
        <img src="{% static "portfolio/sanjeev.png" %}" width="68" height="55" class="d-inline-block align-top align-left" alt="Sanjeev's Logo" class="img-fluid">
        </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-right" id="navbarNav">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a role="button" href="https://ssanjeev.pythonanywhere.com/" class="btn btn-primary">Sanjeev's Write</a>
          </li>

          <li class="nav-item float-md-right float-sm-right">
            <a class="nav-link" href="{% static "portfolio/Sanjeev's_Resume .pdf" %}"><i class="fa fa-file-pdf-o" style="font-size:32px;color:blue"></i></a>
          </li>
          <li class="nav-item float-md-right float-sm-right">
            <a class="nav-link" href="https://www.linkedin.com/in/sanjeev-singh1/" target="_blank"><i class="fab fa-linkedin" style="font-size:32px;color:blue"></i></a>
          </li>

          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="float-md-right float-sm-right btn btn-primary">Reader's Portal</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/dele.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <script src="https://kit.fontawesome.com/cbbb7575de.js" crossorigin="anonymous"></script>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}" >

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/sanjeev.png" %}">

  <title>Sanjeev's</title>
</head>

<body>


  <nav id="topNav" class="clearfix fixed-top navbar navbar-expand-sm navbar-light">
    <div class="container">

        <a class="navbar-brand" href="{% url 'media' %}">
        <img src="{% static "portfolio/sanjeev.png" %}" width="68" height="55" class="d-inline-block align-top align-left" alt="Sanjeev's Logo" class="img-fluid">
        </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-right" id="navbarNav">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a role="button" href="https://ssanjeev.pythonanywhere.com/" class="btn btn-primary">Sanjeev's Write</a>
          </li>

          <li class="nav-item float-md-right float-sm-right">
            <a class="nav-link" href="{% static "portfolio/Sanjeev_Resume.pdf" %}"><i class="fa fa-file-pdf-o" style="font-size:32px;color:blue"></i></a>
          </li>
          <li class="nav-item float-md-right float-sm-right">
            <a class="nav-link" href="https://www.linkedin.com/in/sanjeev-singh1/" target="_blank"><i class="fab fa-linkedin" style="font-size:32px;color:blue"></i></a>
          </li>

          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="float-md-right float-sm-right btn btn-primary">Reader's Portal</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/homepage.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" />

<div class="row justify-content-center my-3">
  <div class="col-5">
      <br>
   <p id="fadeout"> <img src="{% static 'portfolio/giphy.gif' %}" class="img-fluid"></p>


  </div>
</div>
<!-- Fluid jumbotron -->
<div class="jumbotron jumbotron-fluid container">
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Check out  <a class="nav-link" href="https://ssanjeev.pythonanywhere.com/">Sanjeev's Write</a> and put there something interesting.</h1>
    <h1> Thanks for your visit🙏!</h1>
  </div>
</div>
</div>



<h2 class="mt-5">My Recent Projects 🚧</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}" target="_blank">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>


  <!-- PHOTO GALLERY -->
  <section id="gallery" class="py-5">
    <div class="container">
      <h1 class="text-center">My couple of photographs 📷</h1>
      <p class="text-center">Click on photograph to chide another photograph!</p>
      <div class="row mb-4">
        <div class="col-md-4">
          <a href="{% static 'portfolio/eight.JPG' %}" data-toggle="lightbox" data-gallery="img-gallery" data-height="560"
            data-width="560">
            <img src="{% static 'portfolio/one.jpg' %}" alt="" class="img-fluid">
          </a>
        </div>

        <div class="col-md-4">
          <a href="{% static 'portfolio/seven.JPG' %}" data-toggle="lightbox" data-gallery="img-gallery" data-height="561"
            data-width="561">
            <img src="{% static 'portfolio/two.jpg' %}" alt="" class="img-fluid">
          </a>
        </div>

        <div class="col-md-4">
          <a href="{% static 'portfolio/three.jpg' %}" data-toggle="lightbox" data-gallery="img-gallery" data-height="562"
            data-width="562">
            <img src="{% static 'portfolio/ten2.jpg' %}" alt="" class="img-fluid">
          </a>
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-md-4">
          <a href="{% static 'portfolio/nine.JPG' %}" data-toggle="lightbox" data-gallery="img-gallery" data-height="563"
            data-width="563">
            <img src="{% static 'portfolio/four.jpg' %}" alt="" class="img-fluid">
          </a>
        </div>

        <div class="col-md-4">
          <a href="{% static 'portfolio/ten3.JPG' %}" data-toggle="lightbox" data-gallery="img-gallery" data-height="564"
            data-width="564">
            <img src="{% static 'portfolio/five.jpg' %}" alt="" class="img-fluid">
          </a>
        </div>

        <div class="col-md-4">
          <a href="{% static 'portfolio/ten1.jpg' %}" data-toggle="lightbox" data-gallery="img-gallery" data-height="565"
            data-width="565">
            <img src="{% static 'portfolio/six.jpg' %}" alt="" class="img-fluid">
          </a>
        </div>
      </div>
    </div>
  </section>

<div class="row justify-content-center my-3">
<h2>For More Images Follow @ </h2>
  <a href="https://www.instagram.com/sanjeev_ssingh/" target="_blank">
  <img src="https://www.brandchannel.com/wp-content/uploads/2016/05/instagram-new-logo-may-2016.jpg" width="50" height="50"  class="img-fluid">
  </a>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

<!--<script>-->

<!--$("#fadeout").fadeOut(3000);-->

<!--$('#fadeout').hide().load(function () {-->
<!--    $(this).fadeIn(2000);-->
<!--});-->


<!--$("#fadeout").bind("load", function (e) {  e.preventDefault(); $(this).fadeOut(); });-->

<!--$('#fadeout').click(function(e) {-->
<!--    e.preventDefault();-->
<!--    $('#fadeout').fadeOut('slow', function() {-->
<!--        $(this).html($('#fadeout').html()).fadeIn('fast');-->
<!--    });-->
<!--});-->

<!--</script>-->


<script>
    // Lightbox Init
    $(document).on('click', '[data-toggle="lightbox"]', function (event) {
      event.preventDefault();
      $(this).ekkoLightbox();
    });
</script>

{% endblock %}